---
resources:
  - name: sqa-connector-maven-project
    type: git
    icon: github
    source:
      uri: ((GIT_URL))
      branch: ((BRANCH_NAME))

jobs:
  # Unit Testing of the source files
  - name: "build-job"
    serial: true

    plan:
      - do:
          - get: sqa-connector-maven-project
            trigger: true

          - task: build-job
            privileged: true

            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: maven
                  tag: latest

              inputs:
                - name: sqa-connector-maven-project

              params:
                branch: ((BRANCH_NAME))

              run:
                path: /bin/bash
                args:
                  - -exec
                  - |
                    cd sqa-connector-maven-project/connector
                    mvn test

  # Building the clean maven project & Executing the built jar file
  - name: "deploy-job"
    serial: true

    plan:
      - do:
          - get: sqa-connector-maven-project
            passed: [build-job]
            trigger: true

          - task: deploy-job
            privileged: true

            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: maven
                  tag: latest

              inputs:
                - name: sqa-connector-maven-project

              outputs:
                - name: built-artifact

              params:
                branch: ((BRANCH_NAME))

              run:
                path: /bin/bash
                args:
                  - -exec
                  - |
                    cd sqa-connector-maven-project/connector
                    mvn clean install -U -X
                    java -jar target/connector-1.0-jar-with-dependencies.jar ((EXEC_TOKEN)) ((BUILD_API)) ((STATUS_API)) ((KILL_API)) ((THRESHOLD)) ((VERBOSE))